---
title: "Defining a Migrant"
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(sdodemog)
library(tidycensus)
library(scales)
library(survey)

# latest pep vintage we can use for this project
co_pums_to_model <- get_pums(
    variables = c("PUMA", "SEX", "MIG", "MIGSP",
                "AGEP", "SCHL", "WAGP", "POBP", 
                "COW", "ESR", "MAR", "NOC"),
    state = "CO",
    survey = "acs5",
    year = 2024,
    rep_weights = "person"
)
```

```{r message=FALSE, warning=FALSE}
co_pums_recoded <- co_pums_to_model %>%
  mutate(
    emp_type = case_when(
      COW %in% c("1", "2") ~ "private",
      COW %in% c("3", "4", "5") ~ "public",
      TRUE ~ "self"
      ), 
    child = case_when(
      NOC > 0 ~ "yes",
      TRUE ~ "no"
    ),
    married = case_when(
      MAR == 1 ~ "yes",
      TRUE ~ "no"
    ),
    college = case_when(
      SCHL %in% as.character(21:24) ~ "yes",
      TRUE ~ "no"
    ),
    sex = case_when(
      SEX == 2 ~ "female",
      TRUE ~ "male"
    ),
    migrated = case_when(
      MIG == 1 ~ 0,
      TRUE ~ 1
    ),
    migrated_state = case_when(
      MIGSP != "N" & MIGSP != "008" ~ 1,
      TRUE ~ 0
    )
  ) %>%
    mutate(WAGP = as.numeric(WAGP))%>%
    mutate(AGEP = as.numeric(AGEP)) %>%
    mutate(NATIVE = POBP == "008")

co_model_svy <- co_pums_recoded %>% 
  to_survey() %>%
  filter(
    ESR == 1,   # civilian employed
    WAGP > 0,   # earned wages last year
    AGEP >= 25,
    AGEP <= 49
  ) %>%
  rename(age = AGEP, wages = WAGP)
```

```{r message=FALSE, warning=FALSE}
migration_model <- svyglm(
  formula = NATIVE ~ log(wages) + sex + age + emp_type + 
    child + married + college + 
      PUMA,
  design = co_model_svy,
  family = quasibinomial()
) 

migration_model <- svyglm(
  formula = NATIVE ~ sex,
  design = co_model_svy,
  family = quasibinomial()
) 
```

```{r}
summary(migration_model)
```